name: My First CI
on: [push]

jobs:
 hello_from_the_other_side:
  runs-on: ubuntu-latest
  steps:
   - run: echo "Hello, CI/CD World!"
   - run: echo "Hello number 2 from fega"
   - run: echo "We are finished for now"
